### ISSUE TITLE
Flag downloader downloads error page

### ISSUE THREAD

**Issue by bauerj** [ovpn-to/oVPN.to-Client-Software#11]
I've got a `uk.png` containing

    <?xml version="1.0" encoding="iso-8859-1"?>.<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN".         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">.<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">. <head>.  <title>404 - Not Found</title>. </head>. <body>.  <h1>404 - Not Found</h1>. </body>.</html>.

in the `ico/flags` directory. Because `uk` is not valid according to ISO 3166-1 alpha-2 there is no flag icon in famfamfam called `uk.png` but `gb.png`.

**Comment by ovpn-to** [comment]
thank you, uk/gb filename fixed.
