### ISSUE TITLE
Enabling server info hides server window completely

### ISSUE THREAD

**Issue by frk1** [ovpn-to/oVPN.to-Client-Software#135]
When I enable server info the server window/list completely disappears and you can't get it show anymore - until you disable the option.
In debug mode it shows this error when trying to open the window with the option enabled:

```(258.737):(d4) def mainwindow_ovpn_server: for cellid,cellname in failed , exception = ''in <string>' requires string as left operand, not int'```

I've had this bug for quite some versions now, and I don't know why it works on my laptop but does not work on this machine. Seems quite random to me.

I have a video but chose not to post the link publicly since it contains the server ips. If you need it just tell me where to mail it or if you want I can just post it here.

**Comment by ovpn-to** [comment]
this should be fixed with 0.8.8 release now

**Comment by ovpn-to** [comment]
https://board.ovpn.to/v4/index.php?thread/57314-ovpn-client-for-windows-beta-binary-releases/&postID=69910#post69910

**Comment by frk1** [comment]
It's still happening in 0.8.8 for me:

````(83.811):(d4) def cb_destroy_mainwindow
(83.77):(d4) def destroy_mainwindow()
(83.769):(d4) def rebuild_mainwindow_glib: self.mainwindow_ovpn_server() == False
(83.768):(d4) def mainwindow_ovpn_server: for cellid,cellname in failed , exception = ''in <string>' requires string as left operand, not int'
(83.767):(d4) def cellname = 'IPv4'
(83.766):(d4) def mainwindow_ovpn_server: cellid,cellname = '3,IPv4'
(83.765):(d4) def cellname = 'Server'
(83.764):(d4) def mainwindow_ovpn_server: cellid,cellname = '2,Server'
(83.763):(d4) def mainwindow_ovpn_server: enter for cellid,cellname in ...
(83.758):(d4) def mainwindow_ovpn_server()```

**Comment by frk1** [comment]
I take that back, it seems like just installing the new version is not enough. You have to uninstall the old (buggy) version and **delete** the folder (since some dll stays in the folder, along with all config files).

After a fully clean install of 0.8.8 it now works as expected, weird nevertheless.

**Comment by ovpn-to** [comment]
maybe just disabling / enabling the serverinfo option (or any other, to trigger options.cfg rewrite) would do it too, or manually removing the "" from options.cfg entry mainwindowshowcells = "[x,y,z,..]"

**Comment by ovpn-to** [comment]
did you try to change any option before clean un/install or only tried to open serverwindow?

**Comment by frk1** [comment]
Yes I tried turning server info on and off again to see if that changed anything. It didn't, it only started working after the reinstall.

**Comment by ovpn-to** [comment]
added and tested an autofix with updated release 0.8.8

thank you!
