### ISSUE TITLE
OpenVPN Version Error

### ISSUE THREAD

**Issue by MertcanGokgoz** [ovpn-to/oVPN.to-Client-Software#8]
i open ovpn.to client software not work for me always error "please update openvpn software"but my openvpn version "openvpn-install-2.3.7-I603-x86_64"

how to fix this issue

**Comment by ovpn-to** [comment]
dont know, dont get this error.

**Comment by MertcanGokgoz** [comment]
![error](http://puu.sh/jlhSU/03483c4697.jpg)

ovpn_client.exe log output

C:\Users\Mert\AppData\Roaming\ovpn\bin\client\dist\ovpn_client.exe:2229: GtkWarning: inner_clipboard_window_procedure: assertion `success' failed
C:\Users\Mert\AppData\Roaming\ovpn\bin\client\dist\ovpn_client.exe:2229: GtkWarning: inner_clipboard_window_procedure: assertion `success' failed

cient_debug log output

DEBUG_LOG START
Sat Aug 01 15:03:23 2015: win_pre3_load_profile_dir_vars loaded
Sat Aug 01 15:03:23 2015: def check_config_folders: userid found
Sat Aug 01 15:03:23 2015: def check_config_folders :True
Sat Aug 01 15:03:23 2015: ['Ethernet 2', 'Wi-Fi', 'Ethernet']
Sat Aug 01 15:03:23 2015: def win_detect_openvpn: C:\Program Files\OpenVPN\bin\openvpn.exe
Sat Aug 01 15:03:23 2015: Please update your openVPN Version to
x86: https://swupdate.openvpn.net/community/releases/openvpn-install-2.3.7-I603-i686.exe
x64: https://swupdate.openvpn.net/community/releases/openvpn-install-2.3.7-I603-x86_64.exe
Sat Aug 01 15:03:26 2015: def win_detect_openvpn: Failed

**Comment by ovpn-to** [comment]
thank you, will release more debugging version tonight.

**Comment by ovpn-to** [comment]
can you give me an output from: command-line (cmd.exe)  --> openvpn.exe --version?

**Comment by MertcanGokgoz** [comment]
output is 
![version](http://puu.sh/jlkCR/c473c91433.png)

x64: https://swupdate.openvpn.net/community/releases/openvpn-install-2.3.7-I603-x86_64.exe

**Comment by ovpn-to** [comment]
please try:
Binary: https://vcp.ovpn.to/files/ovpn_cli/ovpn_client_v026_p8.exe
SHA256: 36f69b12b33b412ef0776dde5ac8174bb5f01e44fb1b7a80da4756c3961920f7
File size: 7.0 MB ( 7365848 bytes )

**Comment by MertcanGokgoz** [comment]
nope again error

**Comment by ovpn-to** [comment]
Binary: https://vcp.ovpn.to/files/ovpn_cli/ovpn_client_v026_p9.exe
SHA256: 98d44c29b7f211a68391b51daf8631fc1049904ed33c9e752413d6280d6d9467
File size: 7.0 MB ( 7365846 bytes )

thank you for testing

**Comment by MertcanGokgoz** [comment]
thank you for everything working now
